version: '3.8'

services:
  # MySQL数据库
  mysql:
    image: mysql:8.0
    container_name: cloud-scheduler-mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: cloud_scheduler
      MYSQL_USER: scheduler
      MYSQL_PASSWORD: schedulerpass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - scheduler-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Redis缓存
  redis:
    image: redis:7-alpine
    container_name: cloud-scheduler-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - scheduler-network
    restart: unless-stopped

volumes:
  mysql_data:
  redis_data:

networks:
  scheduler-network:
    driver: bridge